title: Categories
modelClass: Hessel\Activiteiten\Models\Category
list: $/hessel/activiteiten/models/category/columns.yaml
recordUrl: 'hessel/activiteiten/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
